### ISSUE TITLE
Cannot compile with fox 1.7.82

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#107]
```
In file included from /home/nerijus/rpmbuild/BUILD/gogglesmm-1.2.2/gap/ap_defs.h:53,
                 from /home/nerijus/rpmbuild/BUILD/gogglesmm-1.2.2/gap/plugins/ap_aiff.cpp:19:
/home/nerijus/rpmbuild/BUILD/gogglesmm-1.2.2/gap/fox.h:60:10: fatal error: FXMemMap.h: No such file or directory
```

**Comment by sanderjansen** [comment]
Thanks. Will have to see what has changed in FOX

**Comment by gogglesguy** [comment]
Support added in development branch

**Comment by nerijus** [comment]
Thank you, it builds ok, but there are no icons in the main window.

**Comment by gogglesguy** [comment]
> Thank you, it builds ok, but there are no icons in the main window.

Works for me (at least the build-in icon theme), so need more details

**Comment by nerijus** [comment]
Just built version 1.2.3, still no icons. Where are the icons taken from? I am building rpm package with my modified spec file (I can attach it if needed), the files in rpm are:
```
$ rpm -ql gogglesmm
/usr/bin/gogglesmm
/usr/lib/.build-id
/usr/lib/.build-id/95
/usr/lib/.build-id/95/780271b7ad51a815fc0a5ef3d94a2427730427
/usr/lib/.build-id/d3
/usr/lib/.build-id/d3/feb4af4e403b0c8fc68b81c2465ca3d87a04fa
/usr/lib/.build-id/df
/usr/lib/.build-id/df/ccb621824f98f3970608db55a3d91904c02aba
/usr/lib/.build-id/f5
/usr/lib/.build-id/f5/58d469f50e705a6a576d9d7fb21de35e03ecc8
/usr/lib64/gogglesmm/libgap_alsa.so
/usr/lib64/gogglesmm/libgap_pulse.so
/usr/lib64/gogglesmm/libgap_wav.so
/usr/share/applications/gogglesmm.desktop
/usr/share/doc/gogglesmm
/usr/share/doc/gogglesmm/AUTHORS
/usr/share/doc/gogglesmm/COPYING
/usr/share/doc/gogglesmm/ChangeLog
/usr/share/doc/gogglesmm/README
/usr/share/icons/hicolor/16x16/apps/gogglesmm.png
/usr/share/icons/hicolor/22x22/apps/gogglesmm.png
/usr/share/icons/hicolor/24x24/apps/gogglesmm.png
/usr/share/icons/hicolor/32x32/apps/gogglesmm.png
/usr/share/icons/hicolor/48x48/apps/gogglesmm.png
/usr/share/icons/hicolor/64x64/apps/gogglesmm.png
/usr/share/icons/hicolor/scalable/apps/gogglesmm.svg
/usr/share/locale/de/LC_MESSAGES/gogglesmm.mo
/usr/share/locale/es/LC_MESSAGES/gogglesmm.mo
/usr/share/locale/fr/LC_MESSAGES/gogglesmm.mo
/usr/share/locale/hu/LC_MESSAGES/gogglesmm.mo
/usr/share/locale/ko/LC_MESSAGES/gogglesmm.mo
/usr/share/locale/pt/LC_MESSAGES/gogglesmm.mo
/usr/share/locale/ru/LC_MESSAGES/gogglesmm.mo
/usr/share/man/man1/gogglesmm.1.gz
/usr/share/metainfo/gogglesmm.appdata.xml
```

**Comment by nerijus** [comment]
spec file:
[gogglesmm.spec.txt](https://github.com/gogglesmm/gogglesmm/files/11304590/gogglesmm.spec.txt)

**Comment by sanderjansen** [comment]
What icon theme did you select in the Preferences?

**Comment by nerijus** [comment]
I didn't, but I see now that Adwaita is selected by default, and when I select Bluecurve the icons reappear.

**Comment by nerijus** [comment]
Didn't want to open a new issue - the new compile error with fox 1.7.83:
```
/home/nerijus/rpmbuild/BUILD/gogglesmm-1.2.4/gap/ap_utils.cpp: In function 'FX::FXbool ap::ap_md5_digest(FX::FXString&)':
/home/nerijus/rpmbuild/BUILD/gogglesmm-1.2.4/gap/ap_utils.cpp:513:36: error: 'value2Digit' is not a member of 'FX::FXString'
  513 |     io[i]=Ascii::toLower(FXString::value2Digit[(digest[d]/16)%16]);
      |                                    ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [gap/CMakeFiles/gap.dir/build.make:426: gap/CMakeFiles/gap.dir/ap_utils.cpp.o] Error 1
```

**Comment by sanderjansen** [comment]
It is fixed in develop, compile with embedded fox in the mean time.

**Comment by nerijus** [comment]
Oops, sorry, forgot to check develop - it compiles, thanks!
